#############################################################################
# LOCAL HOST 
#############################################################################

# GET /agencies
GET http://localhost:3000/agencies

###

# GET /agencies/id

GET http://localhost:3000/agencies/62ca196358b7be242b7bc43c

###

# POST /agencies
# PUT /agencies/id
# DELETE /agencies/id

# GET /cases
# GET /cases/id
# POST /cases
# PUT /cases/id
# DELETE /cases/id

# GET /scores
# GET /scores/id
# POST /scores
# PUT /scores/id
# DELETE /scores/id

# GET /profile
# GET /users
# GET /users/id
# POST /users
# DELETE /users/id


#############################################################################
# HEROKU
#############################################################################

# GET /agencies
# GET /agencies/id
# POST /agencies
# PUT /agencies/id
# DELETE /agencies/id

# GET /cases
# GET /cases/id
# POST /cases
# PUT /cases/id
# DELETE /cases/id

# GET /scores
# GET /scores/id
# POST /scores
# PUT /scores/id
# DELETE /scores/id

# GET /profile
# GET /users
# GET /users/id
# POST /users
# DELETE /users/id