#############################################################################
# LOCAL HOST 
#############################################################################

# GET /agencies
GET http://localhost:3000/agencies

###

# GET /agencies/id

GET http://localhost:3000/agencies/62ca126f58b7be242b7bc42e

###

# GET /cases
GET http://localhost:3000/cases

###

# GET /cases/id
GET http://localhost:3000/cases/62cc38c3c4e0a606952e9ac5

###

# POST /cases   Example of needing authorization
POST http://localhost:3000/cases HTTP/1.1 content-type: application/json

{
  "caseName": "test",
  "victimPicture": "test",
  "victimName": "test",
  "victimAge": "00",
  "caseDate": "00 January 0000",
  "location": "test",
  "caseStatus": "test",
  "websiteURL": "test",
  "agencyInformation": "test"
}

###

# GET /scores
GET http://localhost:3000/scores

###

# GET /scores/id  Example of error message that displays when you don't have the right id
GET http://localhost:3000/scores/62c5ec4ce2a60162506ec1c1

###

# GET /profile   Example of needing Authorization
GET http://localhost:3000/profile

###

#############################################################################
# HEROKU
#############################################################################

# GET /agencies
GET https://fp-matching-game.herokuapp.com/agencies

###
# GET /agencies/id
GET https://fp-matching-game.herokuapp.com/agencies/62ca126f58b7be242b7bc42e

###

# GET /cases
GET https://fp-matching-game.herokuapp.com/cases

###

# GET /cases/id
GET https://fp-matching-game.herokuapp.com/cases/62cc38c3c4e0a606952e9ac5

###

# GET /scores
GET https://fp-matching-game.herokuapp.com/scores

###

# GET /scores/id
GET https://fp-matching-game.herokuapp.com/scores/62cee21254fed75a4fa1c369

###